NODE-1106 changes to update OpenAI node and remove OpenAI Assistant node
n8n-io/n8n-docs pull request #1936
Opened 2024-02-26 18:29 UTC by freakwriter

Followed instructions in: https://linear.app/n8n/issue/NODE-1106/docs-for-ai-node-tweaks-and-openai-node-update, tried to treat each item as a separate commit for quick review.

Two explicit review points:
- There was no list item to update the nav in mkdocs.yml to have the new openai URL instead (integrations/builtin/app-nodes/n8n-nodes-langchain.openai rather than integrations/builtin/app-nodes/n8n-nodes-base.openai.md). I'm assuming the redirect will handle that and that change would come at a future date; I just wanted to note this in case it was a change I should have made.
- Did I format the deprecation warning about OpenAI Assistant properly?

2024-03-04 10:34 UTC, StarfallProjects commented on docs/integrations/builtin/app-nodes/n8n-nodes-langchain.openai.md
> +/// note | OpenAI assistant node
```suggestion
/// note | OpenAI Assistant node
```

2024-03-04 10:37 UTC, StarfallProjects commented on docs/integrations/builtin/app-nodes/n8n-nodes-langchain.openai.md
> +### Related resources
Suggest only having one 'Related resources' section. Please move this into the main one, and rename the link (so we have one general link to the OpenAI API docs, and one specifically for assistants)

2024-03-04 10:37 UTC, StarfallProjects requested changes
See comments on the files

2024-03-04 10:38 UTC, StarfallProjects commented
@freakwriter good catch with the nav in mkdocs.yml: please do go ahead and update this.

2024-03-04 16:37 UTC, freakwriter commented
@StarfallProjects I've incorporated your feedback for n8n-nodes-langchain.openai.md and updated the nav in mkdocs.yml.

2024-03-06 09:24 UTC, StarfallProjects approved these changes

2024-03-06 09:24 UTC, merged