Remove examples section from all trigger nodes
n8n-io/n8n-docs pull request #1937
Opened 2024-02-26 21:20 UTC by freakwriter

Removed Examples section from all trigger nodes, also fixed a typo in Netlify trigger.

2024-03-04 10:31 UTC, StarfallProjects commented
@freakwriter can you also delete the images used in these examples (after checking they're not used elsewhere - but very unlikely that they are)

2024-03-04 10:32 UTC, StarfallProjects requested changes
Please also delete the images used in these examples. They shouldn't be used elsewhere, but double-check.

2024-03-04 15:48 UTC, freakwriter commented
@StarfallProjects I searched for each image path and confirmed I had no results found in the rest of the repo before removing each of the images and the now-empty folders they were in.

I also noticed there were some orphaned files from other nodes that had already had the examples section removed, so I tidied those up as well.

2024-03-06 09:22 UTC, StarfallProjects approved these changes

2024-03-06 09:22 UTC, merged