DOC-717: Remove examples from core nodes
n8n-io/n8n-docs pull request #1946
Opened 2024-03-04 20:22 UTC by freakwriter

- Removed examples or example usage section from core nodes
- Removed now-unused _images files

Question:
_snippets/integrations/builtin/core-nodes/merge/if-merge-branch-execution.md has a screenshot example, but there is also a note to remove once v1 is mature. Should this snippet be removed entirely at this point?

2024-03-06 09:29 UTC, StarfallProjects requested changes
Hiya! A few changes to revert please.

2024-03-06 09:29 UTC, StarfallProjects commented on docs/integrations/builtin/core-nodes/n8n-nodes-base.merge.md
> -
Keep this example

2024-03-06 09:29 UTC, StarfallProjects commented on docs/integrations/builtin/core-nodes/n8n-nodes-base.scheduletrigger.md
> -### Example
Keep this example

2024-03-06 09:29 UTC, StarfallProjects commented on docs/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches.md
> -## Example usage: Read RSS feed from two different sources
Keep this example

2024-03-11 15:27 UTC, ko-support commented
@StarfallProjects I opted to revert all the commits and redo based on your feedback, so at this point the removed examples and related images only touch these files:

- executecommand
- rssfeedread
- ssetrigger
- ssh
- xml

2024-03-11 15:31 UTC, merged