Squish allows
n8n-io/n8n-docs pull request #2084
Opened 2024-05-03 14:35 UTC by ayatnkw

## Changes 
- Rephrasing sentences using 'allows' and anthropomorphism. 

## Related tickets and issues
[Doc-631](https://linear.app/n8n/issue/DOC-631/squish-the-allows)

2024-05-03 14:36 UTC, ayatnkw commented
I'm not sure if it's easier to review in smaller chunks or do it all in one go 🤔 @StarfallProjects

2024-05-07 08:43 UTC, StarfallProjects commented on _snippets/integrations/builtin/node-operations.md
> +* Actions are operations that represent specific tasks or actions within a workflow which you can use to manipulate data, perform operations on external systems, and trigger events in other systems a
```suggestion
* Actions are operations that represent specific tasks or actions within a workflow that you can use to manipulate data, perform operations on external systems, and trigger events in other systems as part of your workflows. When you select an Action, n8n adds a node to your workflow, with the Action operation you chose pre-selected.
```

2024-05-07 08:47 UTC, StarfallProjects commented on _snippets/integrations/builtin/node-operations.md
> +* Actions are operations that represent specific tasks or actions within a workflow which you can use to manipulate data, perform operations on external systems, and trigger events in other systems a
'which' has a comma before it

https://www.dictionary.com/e/that-vs-which/

2024-05-07 08:48 UTC, StarfallProjects commented on docs/advanced-ai/examples/api-workflow-tool.md
> +* [Custom n8n Workflow Tool](/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolworkflow/): plug in n8n workflows as custom tools. In AI, a tool is an interface the AI can use to i
```suggestion
* [Custom n8n Workflow Tool](/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolworkflow/): plug in n8n workflows as custom tools. In AI, a tool is an interface the AI can use to interact with the world (in this case, the data provided by your workflow). The AI model uses the tool to access information beyond its built-in dataset.
```

2024-05-07 08:49 UTC, StarfallProjects commented on docs/advanced-ai/examples/data-google-sheets.md
> +* [Custom n8n Workflow Tool](/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolworkflow/): plug in n8n workflows as custom tools. In AI, a tool is an interface the AI can use to i
```suggestion
* [Custom n8n Workflow Tool](/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolworkflow/): plug in n8n workflows as custom tools. In AI, a tool is an interface the AI can use to interact with the world (in this case, the data provided by your workflow). The AI model uses the tool to access information beyond its built-in dataset.
```

2024-05-07 08:50 UTC, StarfallProjects commented on docs/code/builtin/current-node-input.md
> +	| `$input.context.noItemsLeft` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node, helping you determine whether the node i
```suggestion
	| `$input.context.noItemsLeft` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node. Use this to determine whether the node is still processing items. | :white_check_mark: |
```

2024-05-07 08:56 UTC, StarfallProjects commented on docs/code/builtin/current-node-input.md
> +	| `_input.context.noItemsLeft` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node, helping you determine whether the node i
```suggestion
	| `_input.context.noItemsLeft` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node. Use this to determine whether the node is still processing items. | 
```

2024-05-07 08:56 UTC, StarfallProjects commented on docs/code/builtin/output-other-nodes.md
> +	| `$("<node-name>").context` | Only available when working with the Loop Over Items node. Provides information about what's happening in the node, helping you determine whether the node is still pro
```suggestion
	| `$("<node-name>").context` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node. Use this to determine whether the node is still processing items. | :white_check_mark: |
```

2024-05-07 08:56 UTC, StarfallProjects commented on docs/code/builtin/output-other-nodes.md
> +	| `_("<node-name>").context` | Only available when working with the Loop Over Items node. Provides information about what's happening in the node, helping you determine whether the node is still pro
```suggestion
	| `_("<node-name>").context` | Boolean. Only available when working with the Loop Over Items node. Provides information about what's happening in the node. Use this to determine whether the node is still processing items. | :white_check_mark: |
```

2024-05-07 08:59 UTC, StarfallProjects requested changes
See inline comments

2024-05-13 07:23 UTC, StarfallProjects approved these changes

2024-05-13 07:23 UTC, merged