DOC-853: Credential node overhaul E-G (except Google)
n8n-io/n8n-docs pull request #2090
Opened 2024-05-07 21:04 UTC by freakwriter

Made the same updates here that I made in A-D. Skipped Google for now since that was more involved, but this should be everything else in these letter ranges.

2024-05-09 10:11 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/erpnext.md
>  ## FAQs
```suggestion

```

2024-05-09 10:11 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/erpnext.md
> +### How do I find the subdomain of an ERPNext cloud-hosted account?
```suggestion
## How to find the subdomain of an ERPNext cloud-hosted account
```

2024-05-09 10:12 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/eventbrite.md
> +You'll only need to enter the Credentials Name and select the **Connect my account** button in the OAuth2 credential to connect your Eventbrite account to n8n.
snippet

2024-05-09 10:12 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/eventbrite.md
> +Should you need to configure OAuth2 from scratch or need more detail on what's happening in the OAuth web flow, refer to the instructions in the [Eventbrite API authentication For App Partners docume
```suggestion
If you need to configure OAuth2 from scratch or need more detail on what's happening in the OAuth web flow, refer to the instructions in the [Eventbrite API authentication For App Partners documentation](https://www.eventbrite.com/platform/api#/introduction/authentication/2.-(for-app-partners)-authorize-your-users){:target=_blank .external-link} to set up OAuth.
```

2024-05-09 10:26 UTC, StarfallProjects requested changes
As with the previous batch: couple of small tweaks, use the same snippet for the OAuth note.

And you may have skipped FileMaker?

2024-05-09 10:26 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/getresponse.md
>  ## FAQs
```suggestion

```

2024-05-09 10:26 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/getresponse.md
> +### How do I configure OAuth2 credentials for a local environment?
```suggestion
## Configure OAuth2 credentials for a local environment
```

2024-05-09 10:26 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/github.md
> +You'll only need to enter the Credentials Name and select the **Connect my account** button in the OAuth credential to connect your _Name_ account to n8n.
snippet

2024-05-09 10:26 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/gitlab.md
> +You'll only need to enter the Credentials Name and select the **Connect my account** button in the OAuth credential to connect your _Name_ account to n8n.
snippet

2024-05-13 15:17 UTC, freakwriter commented on docs/integrations/builtin/credentials/gitlab.md
> +You'll only need to enter the Credentials Name and select the **Connect my account** button in the OAuth credential to connect your _Name_ account to n8n.
Updated to snippet.

2024-05-13 16:42 UTC, freakwriter commented
@StarfallProjects yes, I neglected to leave a note. Filemaker has a couple different APIs and I wasn't sure if we were using one specifically or both, so I opted to bump this into my "complex credentials" task and address it once I'd gotten through more of the nodes: https://linear.app/n8n/issue/DOC-842/review-more-complex-creds-pages

I'll be sure to add notes about skipped nodes in the future.

2024-05-14 08:01 UTC, StarfallProjects approved these changes

2024-05-14 08:01 UTC, merged