DOC-866: Credentials Ma-?
n8n-io/n8n-docs pull request #2114
Opened 2024-05-20 20:48 UTC by freakwriter

All credentials from Ma to Me, except for:
- Magento 2 (now an Adobe product and seems like auth has changed significantly)

2024-05-20 20:50 UTC, freakwriter commented
@StarfallProjects could you review only `medium.md` for now? I'm still working on the rest of the PR but that one I had a procedural question on:

Medium is no longer supporting their API and I was trying to determine what the best way to signal that in the docs is. I've added a warning admonition at the top for now but wasn't sure if that was protocol.

2024-05-21 21:56 UTC, freakwriter commented
@StarfallProjects ready for review. One issue of note:

Microsoft had one "general" credential, one for SQL, and one for Entra ID. However, there's a handful of additional credentials now for specific services (Excel, Outlook, Teams, To Do, etc.).

I initially dumped these into the general credential since all those other services' nodes referenced it, but as I've thought about it more, I suspect we should treat Microsoft just as we treat Google, with a subfolder and a separate credentials page for each one. (Which would also require updating cross-references a bunch of places, maybe also updating app links to the docs?)

Let me know if you'd like me to make those changes in this branch; otherwise, I'm happy to document this as a follow-on issue for a future date, since it may require coordinating updates other places.

Aside from that: Could you particularly review any of the database-related nodes (MongoDB, MySQL, Microsoft SQL)? A lot of these are fairly complex credentials and while I've added much more detail than already existed, I'm not sure they're still quite as good as we'd like them to be.

2024-05-22 09:47 UTC, StarfallProjects requested changes
Heya! Got part way through M-N and there's on recurring formatting question: generally UI elements are bold, including ones that users click/select. There are quite a few occurrences of you code formatting them. I might be missing something (if the user types the value in then code format is correct) but I suspect there are just a bunch of things that need tweaking to bold in this PR.

When done, please re-request review

2024-05-22 09:47 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/mailchimp.md
> +> Use an API key if you're writing code that tightly couples _your_ application's data to _your_ Mailchimp account's data. If you ever need to access _someone else's_ Mailchimp account's data, use OA
When quoting, I usually link to the source, like here: https://docs.n8n.io/advanced-ai/examples/understand-tools/

2024-05-22 09:47 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/medium.md
> +Medium has stopped supporting the Medium API. These credentials still appear within n8n, but you won't be able to configure new integrations using them.
```suggestion
Medium has stopped supporting the Medium API. These credentials still appear within n8n, but you can't configure new integrations using them.
```

2024-05-22 09:47 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/microsoft.md
Looking at this, I don't think we need the section for each service. Most of them just point to the generic web flow instructions. Why don't we have:

- The overall Using OAuth2 section
- The web flow section

Then below that any service-specific settings (maybe even grouped in a section with a title like that?)

2024-05-22 09:47 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/mist.md
> +    - `Europe`: Select this option if your cloud environment is in any of the EMEA regions.
Is "Europe" UI text? I'm wondering if this (and a few similar instances) should be bold rather than code formatted?

2024-05-22 09:47 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/mongodb.md
> +- Select `Connection String` as the **Configuration Type**.
As previous comment. I think this should definitely be bold, unless they need to type Values in? But if it's an option they're clicking/selecting in the UI, it should be bold

2024-06-03 15:25 UTC, freakwriter commented
Removed Microsoft and tackled it in its own PR: https://github.com/n8n-io/n8n-docs/pull/2140

I believe the rest of this is ready for review.

2024-06-04 12:48 UTC, StarfallProjects commented on docs/integrations/builtin/credentials/microsoftsql.md
> +Refer to the **Connect to server** table in the [Connect to a SQL Server Instance documentation](https://learn.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-sql-server) for more details
```suggestion
Refer to the **Connect to server** table in the [Connect to a SQL Server Instance documentation](https://learn.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-sql-server){:target=_blank .external-link} for more details on these fields.
```

2024-06-04 13:10 UTC, StarfallProjects approved these changes

2024-06-04 13:11 UTC, merged