add request a built-in node page
n8n-io/n8n-docs pull request #2156
Opened 2024-06-11 12:14 UTC by ayatnkw

### Motivation

Users frequently reach out asking support team about the process for adding a new built-in node. This update aims to provide clearer guidance, addressing common questions before they arise.

2024-06-11 14:04 UTC, StarfallProjects commented
@ayatnkw  One thought: is it worth also mentioning they can use the HTTP Request node for services we don't support with nodes? I could see people hitting this page where https://docs.n8n.io/integrations/custom-operations/ would be useful.

2024-06-13 08:49 UTC, ayatnkw commented
> @ayatnkw One thought: is it worth also mentioning they can use the HTTP Request node for services we don't support with nodes? I could see people hitting this page where https://docs.n8n.io/integrations/custom-operations/ would be useful.

Great point, I'll add this to the page :)

2024-06-21 15:54 UTC, Joffcom requested changes

2024-06-21 15:54 UTC, Joffcom commented on docs/integrations/builtin/request-builtin-node.md
> +If you've created a node you'd like to add as an official node in n8n, open a pull request on [GitHub](https://github.com/n8n-io/n8n){:target=_blank .external-link}. An n8n team member will review it
Can we remove this? Any new node PRs are closed with a message to direct them to comunity nodes.

2024-06-21 15:54 UTC, Joffcom commented on docs/integrations/builtin/request-builtin-node.md
> +For a faster way to make your node available, create a community node and publish it on npm. Refer to [Building community nodes](/integrations/community-nodes/build-community-nodes/) for details. Not
We could possibly add a bit to let users know that we do check community nodes and the anonymous telemetry to help us work out if a node should be added to the main set. When this happens we will reach out to the creator via email or as a github issue.

2024-06-24 10:30 UTC, StarfallProjects requested changes
See comment re custom operations with HTTP node

2024-07-17 13:20 UTC, closed without merging