Add icons for consistency, update node settings options
n8n-io/n8n-docs pull request #2237
Opened 2024-07-16 06:36 UTC by ayatnkw

2024-07-18 18:12 UTC, freakwriter commented on docs/workflows/components/nodes.md
> +	If you select **On App Event**, n8n shows a list of all the supported services. This allows you to browse n8n's integrations and trigger a workflow in response to an event in your chosen service. Bu
@ayatnkw in the spirit of trying to squish the "allows", I've tried a minor rewording here. Wdyt?

2024-07-18 18:18 UTC, freakwriter requested changes
@ayatnkw I've added one rewording here to try to remove "allows", since I remember that being something Deb was working on that I think got assigned over to you. You're welcome to try your own reworking, but I did it as a suggested commit in case that was easier. Other than that, looks good!

2024-07-19 06:50 UTC, ayatnkw commented on docs/workflows/components/nodes.md
> +	If you select **On App Event**, n8n shows a list of all the supported services. This allows you to browse n8n's integrations and trigger a workflow in response to an event in your chosen service. Bu
thanks, looks great!

2024-07-22 15:54 UTC, freakwriter approved these changes

2024-07-23 08:52 UTC, merged