update google calendar node
n8n-io/n8n-docs pull request #2260
Opened 2024-07-23 13:46 UTC by ayatnkw

### Changes
- Updated formatting

2024-07-23 13:50 UTC, ayatnkw commented
@freakwriter I was working on a support related ticket and was going through the docs so I thought I might as well update the docs too. I saw that Google Calendar was set to priority: High but I see that it's tagged medium in the docs, but high in the Node stats google sheet. Do you know why that is?

2024-07-29 14:43 UTC, freakwriter commented
> @freakwriter I was working on a support related ticket and was going through the docs so I thought I might as well update the docs too. I saw that Google Calendar was set to priority: High but I see that it's tagged medium in the docs, but high in the Node stats google sheet. Do you know why that is?

No, probably me just getting cross-eyed updating so many and opening the wrong file. Feel free to update to high!

2024-07-29 14:49 UTC, freakwriter requested changes

2024-07-29 14:49 UTC, freakwriter commented on docs/integrations/builtin/app-nodes/n8n-nodes-base.googlecalendar.md
> +    * **Create**: Add a event to calendar
```suggestion
    * **Create**: Add an event to calendar
```

2024-07-29 14:49 UTC, freakwriter commented on docs/integrations/builtin/app-nodes/n8n-nodes-base.googlecalendar.md
> +View [example workflows and related content](https://n8n.io/integrations/_Name_/){:target=_blank .external-link} on n8n's website.
Now that we have the "Templates and examples" section, we shouldn't need this link in the Related resources section. (I think Debs had already removed it from the most recent template). Can you remove here?

2024-07-29 14:49 UTC, freakwriter commented on docs/integrations/builtin/app-nodes/n8n-nodes-base.googlecalendar.md
> +n8n provides a trigger node for Google Calendar. You can find the trigger node docs [here](/integrations/builtin/trigger-nodes/n8n-nodes-base.n8n-nodes-base.googlecalendartrigger.md/).
```suggestion
n8n provides a trigger node for Google Calendar. You can find the trigger node docs [here](/integrations/builtin/trigger-nodes/n8n-nodes-base.n8n-nodes-base.googlecalendartrigger/).
```

Hyperlinks don't use the .md extension.

2024-07-29 14:49 UTC, freakwriter commented on docs/integrations/builtin/trigger-nodes/n8n-nodes-base.googlecalendartrigger.md
> +View [example workflows and related content](https://n8n.io/integrations/google-calendar-trigger/){:target=_blank .external-link} on n8n's website.
Since you've added the "Templates and examples" section here, delete this related resource link entirely.

2024-08-01 14:14 UTC, freakwriter approved these changes
Looks good!

2024-08-05 14:51 UTC, merged