DOC-975: Update Slack credential to High priority template
n8n-io/n8n-docs pull request #2283
Opened 2024-07-29 16:33 UTC by freakwriter

Also update Slack node and Slack Trigger node

2024-07-29 17:15 UTC, freakwriter commented
@Joffcom could I get you to review this PR? I started out just trying to update the credential but ended up touching the app node and trigger node since I was researching the methods/scopes anyway. I'm a bit on the fence about whether to show the required scopes on the credential page itself or to keep them in the separate node pages...anyway, I want to be sure the node documentation itself is correct, and if you have opinions on the scope stuff, I'm all ears, since I think I wrote myself in circles on this.

2024-08-06 09:28 UTC, ayatnkw commented on docs/integrations/builtin/app-nodes/n8n-nodes-base.slack.md
> +	* **Update User's Profile**
```suggestion
    * **Add** a star to an item.
    * **Delete** a star from an item.
    * **Get Many**: Get a list of an authenticated user's stars.
* **User**
    * **Get** information about a user.
	* **Get Many**: Get a list of users.
    * **Get User's Profile**.
    * **Get User's Status**.
	* **Update User's Profile**.
```

2024-08-06 09:38 UTC, ayatnkw commented on docs/integrations/builtin/credentials/slack.md
> +    - Doesn't work with the [Slack Trigger](/integrations/builtin/trigger-ndoes/n8n-nodes-base.slacktrigger/) node.
```suggestion
    - Required for the [Slack Trigger](/integrations/builtin/trigger-nodes/n8n-nodes-base.slacktrigger/) node.
    - Works with the [Slack](/integrations/builtin/app-nodes/n8n-nodes-base.slack/) node, but not recommended.
- OAuth2:
    - Recommended method for the [Slack](/integrations/builtin/app-nodes/n8n-nodes-base.slack/) node.
    - Doesn't work with the [Slack Trigger](/integrations/builtin/trigger-nodes/n8n-nodes-base.slacktrigger/) node.
```

2024-08-06 09:38 UTC, ayatnkw commented on docs/integrations/builtin/credentials/slack.md
> +    - Doesn't work with the [Slack Trigger](/integrations/builtin/trigger-ndoes/n8n-nodes-base.slacktrigger/) node.
fixing url typo

2024-08-06 09:58 UTC, ayatnkw requested changes
Made a formatting suggestion and fixed a url typo. Also, I noticed a typo in the UI — if you notice something like this while working on the docs, could we maybe start listing them [here](https://linear.app/n8n/issue/DOC-1003/ui-fixes-typos-noticed-while-working-on-the-docs-overhaul)? @freakwriter

2024-08-06 10:11 UTC, Joffcom commented
@freakwriter so I think I would put the scopes at the bottom of the doc maybe in a table as the same scopes will be needed for both oauth and app tokens so we can just link to the table from both.

for OAuth the scopes we will request are below if that helps as well.

```
	'channels:read',
	'channels:write',
	'chat:write',
	'files:read',
	'files:write',
	'groups:read',
	'im:read',
	'mpim:read',
	'reactions:read',
	'reactions:write',
	'stars:read',
	'stars:write',
	'usergroups:write',
	'usergroups:read',
	'users.profile:read',
	'users.profile:write',
	'users:read',
```

2024-08-06 15:18 UTC, freakwriter commented
> Made a formatting suggestion and fixed a url typo. Also, I noticed a typo in the UI — if you notice something like this while working on the docs, could we maybe start listing them [here](https://linear.app/n8n/issue/DOC-1003/ui-fixes-typos-noticed-while-working-on-the-docs-overhaul)? @freakwriter

Yup! I haven't had a good place to capture those so I'm happy to log them wherever.

2024-08-06 15:34 UTC, freakwriter commented
Thanks, @Joffcom , I'm pushing some changes to address this. I appreciate the feedback!

2024-08-15 13:05 UTC, nik8n approved these changes

2024-08-16 08:58 UTC, Joffcom approved these changes

2024-08-19 08:27 UTC, ayatnkw approved these changes

2024-08-19 16:26 UTC, merged