docs: Add `/healthz/readiness` endpoint
n8n-io/n8n-docs pull request #2455
Opened 2024-09-05 13:54 UTC by ivov

Ref https://github.com/n8n-io/n8n/pull/10661

2024-09-05 19:37 UTC, freakwriter requested changes
@ivov Thanks for this PR. Can you review the two suggested commits I added? The first is just to make sure the intro includes the new endpoint. The second is to make our linting tool happier by replacing "does not" with "doesn't".

2024-09-05 19:37 UTC, freakwriter commented on docs/hosting/logging-monitoring/monitoring.md
>  There are two API endpoints you can call to check the status of your instance: `/healthz` and `/metrics`.
```suggestion
There are three API endpoints you can call to check the status of your instance: `/healthz`, `healthz/readiness`, and `/metrics`.
```

2024-09-05 19:37 UTC, freakwriter commented on docs/hosting/logging-monitoring/monitoring.md
> +The `/healthz` endpoint returns a standard HTTP status code. 200 indicates the instance is reachable. It does not indicate DB status. It's available for both self-hosted and Cloud users.
```suggestion
The `/healthz` endpoint returns a standard HTTP status code. 200 indicates the instance is reachable. It doesn't indicate DB status. It's available for both self-hosted and Cloud users.
```

2024-09-06 08:37 UTC, ivov commented
LGTM 👍🏻

2024-09-09 14:09 UTC, freakwriter approved these changes

2024-09-10 14:23 UTC, merged