📚  Add Nodelinter doc
n8n-io/n8n-docs pull request #598
Opened 2021-08-13 07:44 UTC by gpene

2021-08-13 14:08 UTC, ivov requested changes
The whole point of the linter is to save us work, so somewhere should say that a clean lint is a requirement for submitting a PR.

2021-08-13 14:08 UTC, ivov commented on docs/nodes/creating-nodes/nodelinter.md
> +Name this file `nodelinter.config.json` and place it anywhere in your local Nodelinter directory and it will be automatically detected. Alternatively, you can specify the custom config file and locat
> in your local Nodelinter directory

When installing as a dep there is no such dir, config goes in nodes-base

2021-08-13 14:09 UTC, ivov commented on docs/nodes/creating-nodes/nodelinter.md
> +| `--target`        | Path of the file or directory to lint              | Lint a single file:<br>`--target=./packages/nodes-base/nodes/Stripe/Stripe.node.ts` <br><br>Lint all files in a directory:<b
Same fix for the dir

2021-08-13 14:35 UTC, gpene commented
🙏 Thanks @ivov  - updated

2021-08-16 07:29 UTC, ivov approved these changes
🚀

2021-08-16 07:32 UTC, merged