:books: add hubspot app token documentation
n8n-io/n8n-docs pull request #754
Opened 2022-03-13 18:56 UTC by vcrwr

Added docs for https://github.com/n8n-io/n8n/pull/2947

2022-03-13 18:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/n8n-io/n8n-docs?pullRequest=754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n-docs?pullRequest=754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n-docs?pullRequest=754) it.</sub>

2022-03-14 11:02 UTC, StarfallProjects commented on docs/nodes/credentials/Hubspot/README.md
> +## Using APP Token
Using App Token
```suggestion
## Using APP Token
```

2022-03-14 11:06 UTC, StarfallProjects commented
Thank you for contributing! 🎉
I've suggested a couple of phrasing changes.

2022-03-15 13:35 UTC, StarfallProjects requested changes

2022-03-17 15:04 UTC, vcrwr commented on docs/nodes/credentials/Hubspot/README.md
> +## Using APP Token
I used "APP" because it was changed by the merger in the source to Uppercase. So to be consistent with the n8n Naming.

2022-03-21 08:56 UTC, merged