Update Webhook node docs
n8n-io/n8n-docs pull request #847
Opened 2022-05-24 07:38 UTC by lorenanda

- Fixed formatting issues
- Updated/Added node parameters
- Updated screenshots
- Rephrased tutorial instructions, and tweaked the Set expression
- Made links open in new tab

2022-06-06 11:15 UTC, StarfallProjects requested changes
Hi! Thanks for working on this!

I've suggested a bunch of minor style changes.

A couple of additional edits:

- Please replace 'click' with 'select'. The style guide favours select: https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui (and this makes sense with the rise of touchscreens)
- Please optimise the new images (https://tinypng.com/ is quick and free)

Let me know if you have any questions :-)

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +The *Respond to Webhook* node allows controlling the response to incoming webhooks.
```suggestion
The Respond to Webhook node allows you to control the response to incoming webhooks.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +This node can be used in workflows with a [Webhook node](/integrations/core-nodes/n8n-nodes-base.webhook/){:target="_blank"}. To do this, in the Webhook node select the option **Using 'Respond to Web
```suggestion
You can use this node in workflows with a [Webhook node](/integrations/core-nodes/n8n-nodes-base.webhook/){:target="_blank"}. To do this, in the Webhook node select the option **Using 'Respond to Webhook' node** from the **Response** operation.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +    When using [expressions](/code-examples/expressions/){:target="_blank"}, the Respond to Webhook node will only run for the first item in the input data.
```suggestion
    When using [expressions](/code-examples/expressions/){:target="_blank"}, the Respond to Webhook node only runs for the first item in the input data.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **First Incoming Item** — Respond with the first incoming item's JSON.
```suggestion
- **First Incoming Item** - Respond with the first incoming item's JSON.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **Text** — Respond with a text defined in the **Response Body** field.
```suggestion
- **Text** - Respond with the text defined in the **Response Body** field.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **JSON** — Respond with a JSON object defined in the **Response Body** field.
```suggestion
- **JSON** - Respond with a JSON object defined in the **Response Body** field.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **Binary** — Respond with a binary file defined in the **Response Data Source** field.
```suggestion
- **Binary** - Respond with a binary file defined in the **Response Data Source** field.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **No Data** — Don't send a response payload.
```suggestion
- **No Data** - Don't send a response payload.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **Response Code** — Set the [response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status){:target="_blank" .external} to be used.
```suggestion
- **Response Code** - Set the [response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status){:target="_blank" .external} to be used.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +- **Response Headers** — Define the response headers to be sent.
```suggestion
- **Response Headers** - Define the response headers to send.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +[This workflow](https://n8n.io/workflows/1306){:target="_blank"} serves an HTML page when a GET request is made.
```suggestion
[This workflow](https://n8n.io/workflows/1306){:target="_blank"} serves an HTML page in response to a GET request.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +4. Close the *Respond to Webhook* modal and click on **Execute Workflow**.
```suggestion
4. Close the **Respond to Webhook** modal and click on **Execute Workflow**.
```

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +4. Close the *Respond to Webhook* modal and click on **Execute Workflow**.
Should this be two steps? You close the modal, then click execute?

2022-06-06 11:15 UTC, StarfallProjects commented on docs/integrations/core-nodes/n8n-nodes-base.respondToWebhook.md
> +5. Open the **Test URL** from the *Webhook* node in a new browser tab. The browser should now show the page defined in the **Response Body** field of the Respond to Webhook node.
```suggestion
5. Open the **Test URL** from the Webhook node in a new browser tab. The browser should now show the page defined in the **Response Body** field of the Respond to Webhook node.
```

2022-06-13 15:50 UTC, lorenanda commented
Thanks for the review and feedback! I made the suggested edits, hope the explanations and images are better now, but let me know if I should change anything else.

2022-06-20 14:47 UTC, StarfallProjects requested changes
I've just merge main into this branch, and it includes a bunch of additional Vale setup. Can I suggest as an exercise:

1. Get Vale setup locally https://www.notion.so/n8n/Style-tooling-764915624637458f872ef81233e7d4ac (I appreciate Vale is not intuitive - please let me know if you need help)
2. Focusing on just these two docs, try to fix as many issues as possible (I wouldn't expect to fix all of them - sometimes Vale needs to be ignored).
3. And also do a style pass, keeping in mind the style guide basics https://github.com/n8n-io/n8n-docs/wiki/Styles

Perhaps also think about the contents generally. I'm not suggesting a full rewrite at this stage, but maybe we can use these examples as a prompt to start talking about templates for this section.

Let's catch up about this on Wednesday?

2023-02-02 15:09 UTC, closed without merging