Use friendly key names
n8n-io/n8n-docs pull request #970
Opened 2022-10-02 07:46 UTC by rosano

I find these easier to read and more instructive for people less familiar with JSON.

2022-10-03 13:58 UTC, StarfallProjects commented
Friendlier key names is a good suggestion. I'm concerned this might confuse people - I found myself trying to work out where they're from, before remembering the NATO phonetic alphabet is a thing. We probably want to either keep the original somewhat descriptive key names, or choose something even friendlier as an example (use of names in docs examples is a bigger project . . .)

What are your thoughts?

2022-10-03 19:52 UTC, rosano commented
Could also be 'apple', 'banana', 'carrot', 'dog'… I think some beginners might feel uncomfortable changing 'jsonKeyName'  because they thing you need to say 'KeyName' or something. And 'foo' / 'bar' is more legible to programmers. When it's clear that the names are arbitrary and not special keywords, I think people more easily tweak and play.

2022-10-05 09:38 UTC, StarfallProjects commented
Agreed. Would you be willing to update the example to use fruit and vegetables? I think that's a reasonable solution for now.

2022-10-05 21:32 UTC, rosano commented
Done.

I'm a bit confused about how to resolve the conflict as it seems that the whole `Data structure` section was actually not there at the beginning? 🧐 https://github.com/n8n-io/n8n-docs/blob/main/docs/integrations/builtin/core-nodes/n8n-nodes-base.function.md Am I understanding correctly?

2022-10-06 07:45 UTC, StarfallProjects commented
Ah I think you started on this before we merged a fairly large chunk of work. Data structure info lives here now: https://github.com/n8n-io/n8n-docs/blob/main/docs/data/data-structure.md https://docs.n8n.io/data/data-structure/ It looks like we link to it from the function node page.

2022-10-06 11:00 UTC, StarfallProjects commented on docs/data/data-structure.md
> +			"apple": {
```suggestion
			"apple-picture": {
```

Think this makes more sense / is a bit more informative

2022-10-06 11:02 UTC, StarfallProjects commented on docs/courses/level-one/chapter-5/chapter-5.5.md
> +   		 apple: {
```suggestion
   		 apple-picture: {
```

2022-10-06 11:03 UTC, StarfallProjects requested changes
Small suggestion for the binary data key, to make it a bit clearer what's going on there

2022-10-07 07:57 UTC, rosano commented
Looks real friendly 👍🏽

2022-10-07 07:58 UTC, rosano reviewed
Looks real friendly 👍🏽

2022-10-10 08:24 UTC, merged